sku_mapping = {
    "RNBW": "SHAVE-Rainbow",
    "SHV-CSTM": "SHAVE-Custom",
    "BRB": "SHAVE-Barbie",
    "SHRKBT": "SHAVE-SharkAttack",
    "CRML-PPL": "ENE-CaramelApple",
    "WTR": "WATER-Bottle-12oz",
    "STRWBRRY-DRM": "ENE-StrawberryDream",
    "PRTTY-N-PNK": "ENE-PrettyInPink",
    "SKNNY-DP": "BAR-SkinnyDip",
    "SHRK-BT-DR": "ENE-SharkBite",
    "PCH-PSSN": "ENE-Peaches",
    "CSTM": "BAR-Custom",
    "BAR-CUSTOM": "BAR-Custom",
    "BLCKBRRY-VNLL": "ENE-BlackberryVanilla",
    "emint": "BAR-MintToBe",
    "SHAVE-RNBW": "SHAVE-Rainbow",
    "ENE-CRML-PPL": "ENE-CaramelApple",
    "HNG-10": "ENE-Hang10",
    "plain bar": "BAR-Custom",
    "SHAVE-BRB" : "SHAVE-Barbie",
    "SHAVE-CRML-PPL" : "SHAVE-CaramelApple",
    "BAN-PPPRMNT-KSS" : "BAN-PeppermintKiss",
    "ENE-PRTTY-N-PNK" : "ENE-PrettyInPink",
    "ENE-PINACOLADA" : "ENE-PinaColada",
    "ENE-RAZZMATAZZ" : "ENE-Razzmatazz",
    "ENE-STRWBRRY-DRM" : "ENE-StrawberryDream",
    "ENE-HNG-10" : "ENE-Hang10",
    "ENE-PRTTY-N-PNK" : "ENE-PrettyInPink",
    "ENE-SHARK-BITE" : "ENE-SharkBite",
    "ENE-BLCKBRRY-VNLL" : "ENE-BlackberryVanilla",
    "RSPBRRY-BLSH" : "ENE-Razzmatazz",
    "RSPBRRY-LM" : "ENE-Razzmatazz",
    "BAR-TheCrushBar" : "BAR-CrushBar",
    "BAN-TheCrushBar" : "BAN-CrushBar",
    "LMND-JY" : "SHAVE-AlmondJoy",
    "BAR-RiceKrispie'sTreats" : "BAR-RiceKrispiesTreat",
    "BAR-SKNNY-DP": "BAR-SkinnyDip",
    "BAN-SKNNY-DP": "BAN-SkinnyDip",
    "ENE-Customz": "ENE-Custom",
    "ENE-CRML-PPL" : "ENE-CaramelApple",
    "ENE-BoraBora-0" : "ENE-BoraBora",
    "ENE-CarmelApple" : "ENE-CaramelApple",
    "BAR-ALMONDADDICTION" : "BAR-AlmondAddiction",
    "BAR-ALMONDJOY" : "BAR-AlmondJoy",
    "BAR-SKINNYDIP" : "BAR-SkinnyDip",
    "BAN-SKINNYDIP" : "BAN-SkinnyDip",
    "BAR-BUTTERFINGERBLISS" : "BAR-ButterfingerBliss",            
    "BAN-BUTTERFINGERBLISS" : "BAN-ButterfingerBliss",
    "BR-RBSSSN" : "BAR-OreoObsession",
    "SHV-SHRKTTCK" : "SHAVE-SharkAttack",
    "BR-YBBDBBDP" : "BAR-YabbaDabbaDip",
    "BR-TK5" : "BAR-Take5",
    "BR-MNTTB" : "BAR-MintToBe",
    "BR-GMMSMR" : "BAR-GimmeSmore",
    "BR-VRTHRNBW" : "BAR-OverTheRainbow",
    "SHV-RNBW" : "SHAVE-Rainbow",
    "BR-LMNDJY" : "BAR-AlmondJoy",
    "N-RZZMTZZ" : "ENE-Razzmatazz",
    "BR-CSTM" : "BAR-Custom",
    "BN-CSTM" : "BAN-Custom",
    "N-PRTTYNPNK" : "ENE-PrettyInPink",
    "BR-FRDCCRM" : "BAR-FriedIceCream",
    "BR-LMNDDDCTN" : "BAR-AlmondAddiction",
    "N-BRBR" : "ENE-BoraBora",
    "BR-SLTYCRSH" : "BAR-SaltyCrush",
    "N-WNTRCRSH" : "ENE-WinterCrush",
    "BN-TK5" : "BAN-Take5",
    "N-SHRKBT" : "ENE-SharkBite",
    "BN-RCKYRD" : "BAN-RockyRoad",
    "BR-PNTPRFCTN" : "BAR-PeanutPerfection",
    "SHV-LMNDJY" : "SHAVE-AlmondJoy",
    "BR-RCKYRD" : "BAR-RockyRoad",
    "N-PNCLD" : "ENE-PinaColada",
    "N-PCHS" : "ENE-Peaches",
    "BN-LMNDJY" : "BAN-AlmondJoy",
    "BN-BTTRFNGRBLSS" : "BAN-ButterfingerBliss",
    "BR-BTTRFNGRBLSS" : "BAR-ButterfingerBliss",
    "BN-GMMSMR" : "BAN-GimmeSmore",
    "SHV-BRB" : "SHAVE-Barbie",
    "BN-PNTPRFCTN" : "BAN-PeanutPerfection",
    "BN-FRDCCRM" : "BAN-FriedIceCream",
    "N-RBYRD" : "ENE-RubyRed",
    "BN-SLTYCRSH" : "BAN-SaltyCrush",
    "BN-RBSSSN" : "BAN-OreoObsession",
    "N-BLCKBRRYVNLL" : "ENE-BlackberryVanilla",
    "BR-PPPRMNTKSS" : "BAR-PeppermintKiss",
    "N-CSTM" : "ENE-Custom",
    "N-SNNYDY" : "ENE-SunnyDay",
    "BN-SKNNYDP" : "BAN-SkinnyDip",
    "BR-SKNNYDP" : "BAR-SkinnyDip",
    "N-HNG10" : "ENE-Hang10",
    "N-CRMLPPL" : "ENE-CaramelApple",
    "N-STRWBRRYDRM" : "ENE-StrawberryDream",
    "BN-YBBDBBDP" : "BAN-YabbaDabbaDip",
    "BN-PPPRMNTKSS" : "BAN-PeppermintKiss",
    "CCNT-WTR" : "CAN-CoconutWater",
    "ENE-PINACOLADA-0" : "ENE-PinaColada",
    "ENE-PEACHES-0" : "ENE-Peaches",
    "GRINVH" : "SHAVE-Grinch",
    "GRINCH" : "SHAVE-Grinch",
    "WINTER CRUSH" : "ENE-WinterCrush",
    "SHAVE=GRINCH" : " SHAVE-Grinch",
    " SHAVE-GRINCH" : " SHAVE-Grinch",            
    "SHAVE ICE" : "SHAVE-Custom",
    "BN-MNTTB" : "BAN-MintToBe",
    "CARAMEL APPLE ENERGY DRINK" : "ENE-CaramelApple",
    "COCONUT SHAVE ICE" : "SHAVE-Coconut",
    "TAKE 5 SIGNATURE BANANA" : "BAN-Take5",
    "STRAWBERRY DREAM ENERGY DRINK" : "ENE-StrawberryDream",
    "PINA COLADA ENERGY DRINK" : "ENE-PinaColada",
    "HANG 10 ENERGY DRINK" : "ENE-HANG10",
    "PRETTY IN PINK ENERGY DRINK" : "ENE-PrettyInPink",
    "PEACHES ENERGY DRINK" : "ENE-PEACHES",
    "RAZZMATAZZ" : "ENE-Razzmatazz",
    "ALMOND ADDICTION SIGNATURE BANANA" : "BAN-AlmondAddiction",
    "BORA BORA ENERGY DRINK" : "ENE-BoraBora",
    "FRIED ICE CREAM SIGNATURE BAR" : "BAR-FriedIceCream",
    "TAKE 5 SIGNATURE BAR" : "BAR-Take5",
    "MINT TO BE SIGNATURE BAR" : "BAR-MINTTOBE",
    "OREO OBSESSION SIGNATURE BAR" : "BAR-OreoObsession",
    "SALTY CRUSH SIGNATURE BAR" : "BAR-SaltyCrush",
    "ALMOND JOY SIGNATURE BAR" : "BAR-AlmondJoy",
    "RAZZMATAZZ ENERGY DRINK" : "ENE-Razzmatazz",
    "RUBY RED ENERGY DRINK" : "ENE-RubyRed",
    "ROCKY ROAD SIGNATURE BAR" : "BAR-RockyRoad",
    "SUNNY DAY ENERGY DRINK" : "ENE-SunnyDay",
    "GIMME S'MORE SIGNATURE BANANA" : "BAR-GimmeSmore",
    "YABBA DABBA DIP SIGNATURE BAR" : "BAR-YabbaDabbaDip",
    "GIMME S'MORE SIGNATURE BAR" : "BAR-GimmeSmore",
    "PEANUT PERFECTION SIGNATURE BAR" : "BAR-PeanutPerfection",
    "SHARK BITE ENERGY DRINK" : "ENE-SharkBite",
    "ICE CUP" : "ICE-CUP",
    "WINTER CRUSH" : "ENE-WinterCrush",
    "RAZZMATAZZ" : "ENE-Razzmatazz",
    "GRINVH" : "SHAVE-Grinch",
    "GRINCH" : "SHAVE-GRINCH",
    "SHARK BITE" : "ENE-SharkBite",
    "skills jny dip" : "BAR-SkinnyDip",
    "BORA BORA" : "ENE-BoraBora",
    "TAKE 5" : "BAR-Take5",
    "SHAVE-CSTM" : "SHAVE-Custom",
    "WATER-CUPOFICE" : "WATER-IceWaterCup",
    "BAN-CUSTOM" : "BAN-Custom",
    "REF-PRETTY-IN-PINK": "REF-PrettyInPink",
    "REF-STRAWBERRY-COLADA": "REF-StrawberryColada",
    "REF-BORABORA": "REF-BoraBora",
    "BAN-BISCOFF": "BAN-Biscoff",
    "BAR-BISCOFF": "BAR-Biscoff",
    "BAR-DUBAI": "BAR-Dubai",
    "BAN-BISCOFF": "BAB-Dubai",
    "WTR-BTTL": "WATER-Bottle-12oz",
    "BN-LMNDDDCTN" : "BAN-AlmondAddiction",
    "SHAVE-CUSTOM" : "SHAVE-Custom",
    "BAR-VANILLA": "BAR-Vanilla",
    "COF-CB-MAPLE": "COF-CB-Maple",
    "COF-CB-SALTEDCARAMEL": "COF-CB-SaltedCaramel",
    "SHAVE-RAINBOW" : "SHAVE-Rainbow",
    "SHAVE-SHARKATTACK" : "SHAVE-SharkAttack",
    "SHAVE-BARBIE" : "SHAVE-Barbie",
    "N-CRNBRRYFZZ" : "ENE-CranberryFizz",
    "COFF-Custom" : "COF-CB-Custom",   
    "COF-Custom" : "COF-CB-Custom",   
    "BLCK-CLD-BRW": "COF-CB-Cowboy",
    "CF-CRML-HRTBRKR": "COF-CB-SaltedCaramel",
    "CF-FRST-CRSH": "COF-CB-VanillaCrush",
    "CFMPL": "COF-CB-MapleCream",
    "CF-PCN-SCRT-DMRR": "COF-CB-Pecan"
}

def fix_sku(sku):
    if sku in sku_mapping:
        return sku_mapping[sku]
    else:
        return sku
